### PR TITLE
Add editorconfig to suppress diff by indent size

### PR DESCRIPTION
**Pull request by SnO2WMaN**
Add editorconfig to fix excessive diffs due to indent size differences (4 and 2).

### CODE REVIEW

**Comment by LOLBRUHNICE** [comment]
@SnO2WMaN seems like the version you forked was not the latest, the latest version has changed the build script in package.json, you need to fork and create pr again

**Comment by SnO2WMaN** [comment]
Calmly thought, it can't use pnpm in cloudflare, so I lost the motivation to put effort into this PR. if you mind, close this. Thanks.

**Comment by LOLBRUHNICE** [comment]
If you mean cloudflare pages won't automatically install pnpm for deployment, you can change the build script to
`npm i pnpm -g && pnpm install && pnpm build:cf` where the `build:cf` is the script you run the next-on-pages
I tested it and it works fine

Otherwise I don't know what do you mean by can't use pnpm in cloudflare

**Comment by LOLBRUHNICE** [comment]
you can install the next-on-pages from my testBuild branch: https://github.com/LOLBRUHNICE/next-on-pages/tree/testBuild and try it

**Comment by LOLBRUHNICE** [comment]
I will close this pr like you said now

**Pull request closed without merging**
